name: example

environment:  
  sdk: ">=2.0.0 <3.0.0" 

dependencies: 
  typedef_for_fn:
    path: ../typedef_for_fn/

dev_dependencies:
  build_runner: ^1.2.8
  typedef_for_fn_generator:
    path: ../typedef_for_fn_generator/   