name: example

environment:  
  sdk: ">=2.3.0 <3.0.0" 

dependencies: 
  typedef_for_fn:  
    path: ../typedef_for_fn/

dev_dependencies:
  build_runner: ^1.2.8
  built_value_generator: ^6.3.2
  typedef_for_fn_generator:
    path: ../typedef_for_fn_generator/    