name: example

environment:  
  sdk: ">=2.7.0 <3.0.0"

dependencies: 
  typedef_for_fn: ^1.0.0

dev_dependencies:
  build_runner: ^1.2.8
  typedef_for_fn_generator:
    path: ../typedef_for_fn_generator/    