targets:
  $default:
    builders:
      typedef_for_fn_generator|typedef_for_fn:
        enabled: true
 
builders:
  typedef_for_fn:
    target: ":typedef_for_fn_generator"
    import: "package:typedef_for_fn_generator/builder.dart"
    builder_factories: ["typedef_for_fn_generator"]
    build_extensions: {".dart": [".x.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]


# targets:
#   $default:
#     builders:
#       todo_reporter_generator|todo_reporter:
#         enabled: true

# builders:
#   todo_reporter:
#     target: ":todo_reporter_generator"
#     import: "package:todo_reporter_generator/builder.dart"
#     builder_factories: ["todoReporter"]
#     build_extensions: {".dart": [".todo_reporter.g.part"]}
#     auto_apply: dependents
#     build_to: cache
# applies_builders: ["source_gen|combining_builder"]