targets:
  $default:
    builders:
      typedef_for_fn_generator|typedef_for_fn:
        enabled: true
 
builders:
  typedef_for_fn:
    target: ":typedef_for_fn_generator"
    import: "package:typedef_for_fn_generator/typedefForFnBuilder.dart"
    builder_factories: ["typedefForFnBuilder"]
    build_extensions: {".dart": [".typedef.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
    required_inputs: [".valuet2.dart", ".valuet3.dart"]
