name: typedef_for_fn_generator
description: An annotation processor for @TypedefForFn annotations
version: 1.0.0
author: Adrian
# homepage: https://github.com/...

environment:  
  sdk: ">=2.0.0 <3.0.0" 
 
dependencies:  
  build: '>=0.12.0 <2.0.0'  
  source_gen: ^0.9.0  
  typedef_for_fn:    
    path: ../typedef_for_fn/  

dev_dependencies:  
  build_test: ^0.10.0  
  build_runner: '>=0.9.0 <0.11.0'  
  test: ^1.0.0