name: typedef_for_fn_generator
description: An annotation processor for @TypedefForFn annotations
version: 1.0.4-nullsafety4
homepage: https://github.com/atreeon/typedef_for_fn

environment:  
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:  
  build: ^1.6.3
  source_gen: ^0.9.10+3
  typedef_for_fn: ^1.0.1-nnbd
  quiver: ^3.0.0-nullsafety.3
  dartz: ^0.10.0-nullsafety.0
  analyzer: '>=0.40.0 <=1.0.0'

dev_dependencies:  
  # build_test: ^0.10.0  
  build_runner: ^1.2.8
  test: ^1.16.0-nullsafety.16
  