name: typedef_for_fn_generator
description: An annotation processor for @TypedefForFn annotations
version: 1.1.0
homepage: https://github.com/atreeon/typedef_for_fn
publish_to: none

environment:  
  sdk: ^3.1.3
  
dependencies:  
  analyzer: '>=5.12.0 <6.0.0'
  build: ^2.1.0
  dartz: ^0.10.0-nullsafety.0
#  generator_common: ^1.0.0-nullsafety7
  generator_common:
    path: ../../generator_common
  quiver: ^3.0.0-nullsafety.3
  source_gen: ^1.1.1
#  typedef_for_fn: ^1.0.1-nnbd
  typedef_for_fn:
    path: ../typedef_for_fn

dev_dependencies:  
  # build_test: ^0.10.0  
  build_runner: ^2.1.4
  test: ^1.24.2
  