name: typedef_for_fn_generator
description: An annotation processor for @TypedefForFn annotations
version: 1.0.0
homepage: https://github.com/atreeon/typedef_for_fn
 
environment:  
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:  
  build: ^1.1.1
  source_gen: ^0.9.4+7
  typedef_for_fn: ^1.0.0
  quiver: ^2.0.1
  dartz: ^0.8.3
  analyzer: '>=0.35.4 <0.42.0'

dev_dependencies:  
  # build_test: ^0.10.0  
  build_runner: ^1.2.8
  test: ^1.0.0
  