name: typedef_for_fn_generator
description: An annotation processor for @TypedefForFn annotations
version: 1.0.0
author: Adrian
# homepage: https://github.com/...
 
environment:  
  sdk: ">=2.0.0 <3.0.0" 
 
dependencies:  
  build: ^1.1.0 
  source_gen: ^0.9.4 
  typedef_for_fn:    
    path: ../typedef_for_fn/  
  quiver: ^2.0.1 
  adi_helpers: 
    # git: git@bitbucket.org/twistedinferno/adi_helpers.git
    path: ../../adi_helpers/
     
dev_dependencies:  
  build_test: ^0.10.0  
  build_runner: ^1.1.3
  test: ^1.0.0
  